	<tr>
		<td><?php echo $this->escape($this->time);?></td>
		<td><?php echo $this->escape($this->name);?></td>
		<td><?php echo $this->escape($this->email);?></td>
		<td><?php echo $this->escape($this->title);?></td>
	</tr>
	<tr>
		<td colspan="4">
			<?php echo $this->escape($this->text);?>
			<br>
			<!--
			<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$this->id));?>">Редактировать</a>
			<a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$this->id));?>"> Удалить</a>
			-->
		</td>
	</tr>
